
models = [tf.keras.models.load_model('model_0'),
          tf.keras.models.load_model('model_1'),
          tf.keras.models.load_model('model_2'),
          tf.keras.models.load_model('model_3'),
          tf.keras.models.load_model('model_4'),
          tf.keras.models.load_model('model_5'),
          tf.keras.models.load_model('model_6'),
          tf.keras.models.load_model('model_7'),
          tf.keras.models.load_model('model_8'),
          tf.keras.models.load_model('model_9'),
          tf.keras.models.load_model('model_10'),
          tf.keras.models.load_model('model_11'),
          tf.keras.models.load_model('model_12'),
          tf.keras.models.load_model('model_13')]
